(function initializeSharedItemDefinitions(root, factory) {
  const api = factory();
  const namespace = root.NeoNyke = root.NeoNyke || {};
  namespace.content = namespace.content || {};
  Object.assign(namespace.content, api);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function createSharedItemDefinitionsApi() {
  'use strict';

const ITEM_DEFS = {
    neo_knife: {
      key: 'neo_knife',
      name: 'Neo-Knife',
      shortName: 'Knife',
      description: 'Basic melee and bleed-focused melee attacks gain +10% Bleed chance per stack.',
      rarity: 'knight',
      color: '#f4f6fb',
      category: 'knight',
      tags: ['bleed'],
    },
    tooth_of_thorn: {
      key: 'tooth_of_thorn',
      name: 'Tooth of Thorn',
      shortName: 'Drain Ramp',
      description: 'Hits have a chance to drain life: steal a chunk of HP, then keep healing for a few seconds. Procs still arm at full HP. Each stack drains harder; high-level foes resist up to 60%.',
      rarity: 'knight',
      color: '#ffd7e2',
      accent: '#ff6e8b',
      category: 'knight',
      tags: ['drain', 'heal', 'hit'],
    },
    tough_bandaid: {
      key: 'tough_bandaid',
      name: 'Tough Bandaid',
      shortName: 'Patch + Resist',
      description: 'Per stack: defense +0.5% and +2% Bleed chance on basic and bleed-focused melee attacks. Bleed tick damage taken -10% per stack (max -80%); your Bleed timers decay 20% faster per stack (max 3× speed).',
      rarity: 'knight',
      color: '#f0e2cf',
      accent: '#a87555',
      category: 'knight',
      tags: ['defense', 'bleed'],
    },
    orb_of_blood: {
      key: 'orb_of_blood',
      name: 'Orb of Blood',
      shortName: 'Orb',
      description: 'Bleeding enemies take +100% damage per stack.',
      rarity: 'wizard',
      color: '#a857ff',
      category: 'wizard',
      tags: ['bleed', 'damage'],
    },
    hemes_scarf: {
      key: 'hemes_scarf',
      name: "Heme's Scarf",
      shortName: 'Scarf',
      description: 'Per stack: nearby enemies always bleed, and taking a hit bleeds you too. After 10 kills, the charged scarf can discharge below 50 HP, draining active bleed into healing for 3 seconds. Then it must earn 10 kills again.',
      rarity: 'god',
      color: '#ff4256',
      accent: '#35ff6f',
      category: 'god',
      tags: ['bleed', 'heal', 'breaker'],
    },
    insurance: {
      key: 'insurance',
      name: 'Insurance',
      shortName: 'Insure',
      description: 'If a hit pushes you below half health, this is consumed and must recharge with kills.',
      rarity: 'knight',
      color: '#f4f6fb',
      category: 'knight',
      tags: ['charge', 'defense'],
    },
    gold_vac: {
      key: 'gold_vac',
      tool: true,
      name: 'Gold Vac',
      shortName: 'Vac x1',
      description: 'Tool: runs for 2 minutes. Automatically vacuums pickups from across the room and doubles coin pickup value. Each extra stack adds +30s and +50% coin value.',
      rarity: 'knight',
      color: '#ffe07a',
      accent: '#fff6c7',
      category: 'knight',
      tags: ['tools', 'loot', 'coin', 'utility'],
    },
    copycat_charm: {
      key: 'copycat_charm',
      name: 'Copycat Charm',
      shortName: 'Item x2',
      description: '30% chance per stack to duplicate an item pickup, capped at 75%.',
      rarity: 'god',
      color: '#f5efff',
      accent: '#c8a8ff',
      category: 'god',
      tags: ['loot', 'item', 'utility'],
    },
    crit_charm: {
      key: 'crit_charm',
      name: 'Crit Charm',
      shortName: 'Hit Crit',
      description: '+2.5% flat crit chance per stack. Every few kills, also surge +4% crit chance per stack for 4s. (3/5/7 kills on easy/normal/hard).',
      rarity: 'knight',
      color: '#ffffff',
      category: 'knight',
      tags: ['crit', 'charge'],
    },
    copper_penny: {
      key: 'copper_penny',
      name: 'Copper Penny',
      shortName: 'Volt %',
      description: 'Electric attacks deal +20% damage per stack and build Static on enemies — a charge that stacks, deals damage over time, and arcs to nearby foes.',
      rarity: 'knight',
      color: '#e08a4a',
      accent: '#ffd27d',
      category: 'knight',
      tags: ['damage', 'status', 'lightning'],
    },
    attack_servo: {
      key: 'attack_servo',
      name: 'Attack Servo',
      shortName: 'AS %',
      description: 'Attack speed +8% per stack.',
      rarity: 'knight',
      color: '#eef5ff',
      category: 'knight',
      tags: ['speed'],
    },
    enemy_magnet: {
      key: 'enemy_magnet',
      name: 'Enemy Magnet',
      shortName: 'Homing +5%',
      description: 'Projectile homing +15% per stack, plus an extra 2% × stacks per stack (ramps up fast as you invest). Gives player bullets homing.',
      rarity: 'knight',
      color: '#dff6ff',
      accent: '#7ad8ff',
      category: 'knight',
      tags: ['projectile', 'homing', 'utility'],
    },
    keen_eye: {
      key: 'keen_eye',
      name: 'Keen Eye',
      shortName: 'Kill Focus',
      description: 'Charge on 10 kills. When full, the next kill grants Glitter for 7s: +20% crit chance and +2.5% critical damage per stack.',
      rarity: 'knight',
      color: '#f7fbff',
      category: 'knight',
      tags: ['crit', 'charge'],
    },
    chrono_spring: {
      key: 'chrono_spring',
      name: 'Chrono Spring',
      shortName: 'Kill Haste',
      description: 'Charge on 7 kills. When full, the next kill grants +16% attack speed per stack for 6s.',
      rarity: 'knight',
      color: '#e6f6ff',
      category: 'knight',
      tags: ['speed', 'charge'],
    },
    scholar_seal: {
      key: 'scholar_seal',
      name: 'Scholar Seal',
      shortName: 'XP +15%',
      description: 'Gain 15% more XP on enemy kill per stack. Shops also get cheaper the closer you are to leveling up (up to -10% at the brink of a level).',
      rarity: 'knight',
      color: '#d0ecff',
      category: 'knight',
      tags: ['xp'],
    },
    scholar_cap: {
      key: 'scholar_cap',
      name: "Scholar's Cap",
      shortName: 'Level Edge',
      description: 'Deal up to +45% damage per stack as you get closer to leveling up.',
      rarity: 'wizard',
      color: '#b49cff',
      category: 'wizard',
      tags: ['xp', 'damage', 'wizard'],
    },
    push_man: {
      key: 'push_man',
      name: 'Push Man',
      shortName: 'KB +18%',
      description: 'Knockback +18% per stack.',
      rarity: 'knight',
      color: '#fff2cf',
      category: 'knight',
      tags: ['knockback'],
    },
    titan_heart: {
      key: 'titan_heart',
      name: 'Titan Heart',
      shortName: 'Max HP +8%',
      description: 'Max HP +8% per stack on pickup.',
      rarity: 'knight',
      color: '#ffd9de',
      category: 'knight',
      tags: ['hp'],
    },
    weapon_fatigue: {
      key: 'weapon_fatigue',
      name: 'Weapon Fatigue',
      shortName: 'Slow',
      description: 'Hits have a 5% chance per stack to slow enemies, plus a 2% chance per stack to briefly freeze them solid (melee or ranged).',
      rarity: 'knight',
      color: '#e7fbff',
      category: 'knight',
      tags: ['slow', 'freeze'],
    },
    generic_health_item: {
      key: 'generic_health_item',
      name: 'Generic Health',
      shortName: 'Heal 5%',
      description: 'On kill, restore 5% of your current HP per stack, capped by max HP. With another healing item, overhealing has a chance to grant a shield.',
      rarity: 'knight',
      color: '#d9ffe5',
      category: 'knight',
      tags: ['heal', 'charge'],
    },
    snake_knife: {
      key: 'snake_knife',
      name: 'Snake Knife',
      shortName: 'Poison +10%',
      description: 'Hits have a 10% chance per stack to poison enemies (melee or ranged). Poison has a natural 1% chance to spread to a nearby foe each tick.',
      rarity: 'knight',
      color: '#d7ffbf',
      category: 'knight',
      tags: ['poison'],
    },
    confuse_ray: {
      key: 'confuse_ray',
      name: 'Confuse Ray',
      shortName: 'Stun 15%',
      description: 'Hits have a 15% chance per stack to stun enemies no matter what, capped at 75%. Every hit also has a flat 5% chance to make the enemy think you turned invisible (it loses track of you and wanders).',
      rarity: 'knight',
      color: '#d8f0ff',
      category: 'knight',
      tags: ['stun', 'hit'],
    },
    overclocked_watch: {
      key: 'overclocked_watch',
      name: 'Overclocked Watch',
      shortName: 'Charge x2',
      description: '20% chance per stack for kill charge progress to count twice instead of once. Also shaves 2% per stack off the buff enemies gain over time (capped at 30%).',
      rarity: 'knight',
      color: '#f0fbff',
      category: 'knight',
      tags: ['charge', 'kill'],
    },
    charged_adapter: {
      key: 'charged_adapter',
      tool: true,
      name: 'Charged Adapter',
      shortName: 'Warp F',
      description: 'Charge requirement -1 per stack. When charged, press its tool slot key (outside boss rooms) to spend 50% coins and warp to the ladder room (next floor path).',
      rarity: 'wizard',
      color: '#b66cff',
      category: 'wizard',
      tags: ['charge', 'mobility'],
    },
    pew_pew_box: {
      key: 'pew_pew_box',
      tool: true,
      name: 'Pew Pew Box',
      shortName: 'Missile Box',
      description: 'Tool. Fire homing missiles for 8 seconds. Extra stacks add duration, missiles per volley, and missile damage.',
      rarity: 'wizard',
      color: '#ffe06f',
      accent: '#ff8f3d',
      category: 'wizard',
      tags: ['tools', 'projectile', 'missile', 'wizard'],
    },
    skizzard_tail: {
      key: 'skizzard_tail',
      tool: true,
      name: 'Skizzard Tail',
      shortName: 'Regen',
      description: 'Tool. Regenerate health for 5 seconds. Extra stacks add duration and stronger healing ticks.',
      rarity: 'wizard',
      color: '#8fffd2',
      accent: '#6fd7ff',
      category: 'wizard',
      tags: ['tools', 'regen', 'heal', 'wizard'],
    },
    zap_to_extreme: {
      key: 'zap_to_extreme',
      tool: true,
      name: 'Zap to the Extreme',
      shortName: 'Zap Extreme',
      description: 'Tool. Chain lightning around you for 10 seconds. Extra stacks add duration, range, targets, and damage.',
      rarity: 'wizard',
      color: '#8dd4ff',
      accent: '#f4fbff',
      category: 'wizard',
      tags: ['tools', 'lightning', 'aoe', 'wizard'],
    },
    panic_button: {
      key: 'panic_button',
      tool: true,
      name: 'Panic Button',
      shortName: 'Panic',
      description: 'Tool. Clear statuses, shove enemies away, and gain brief invulnerability. Extra stacks increase radius, shove, damage, stun, and invulnerability time.',
      rarity: 'wizard',
      color: '#f4f6fb',
      accent: '#ff6b7f',
      category: 'wizard',
      tags: ['tools', 'defense', 'knockback', 'wizard'],
    },
    mid_sweepy_box: {
      key: 'mid_sweepy_box',
      tool: true,
      name: 'Mid Sweepy Box',
      shortName: 'Sweep Mines',
      description: 'Tool. Sweep thorn mines around you for 6 seconds. Extra stacks add duration, mines per tick, blast size, damage, and bleed.',
      rarity: 'wizard',
      color: '#ffd7e2',
      accent: '#ff6e8b',
      category: 'wizard',
      tags: ['tools', 'bleed', 'mine', 'wizard'],
    },
    sparkle_charm: {
      key: 'sparkle_charm',
      tool: true,
      name: 'Sparkle Charm',
      shortName: 'Sparkle',
      description: 'Tool. Sparkle the nearest 5 enemies for 6 seconds. Every hit against a sparkled enemy is a guaranteed crit. Extra stacks mark more enemies for longer.',
      rarity: 'wizard',
      color: '#ffe8a3',
      accent: '#ffd05a',
      category: 'wizard',
      tags: ['tools', 'crit', 'wizard'],
    },
    churu_stick: {
      key: 'churu_stick',
      tool: true,
      name: 'Churu Stick',
      shortName: 'Heal 30%',
      description: 'Tool. Instantly heal 30% of max HP. Long 40s cooldown. Auto-fires when health drops below 15%. Extra stacks shorten the cooldown.',
      rarity: 'wizard',
      color: '#ffb6d5',
      accent: '#ff7eb0',
      category: 'wizard',
      tags: ['tools', 'heal', 'regen', 'wizard'],
    },
    explosive_jelly: {
      key: 'explosive_jelly',
      name: 'Explosive Jelly',
      shortName: 'AOE +20%',
      description: 'All player AOE ranges are increased by 20% per stack.',
      rarity: 'wizard',
      color: '#ffb27d',
      category: 'wizard',
      tags: ['aoe', 'wizard'],
    },
    dragon_orb: {
      key: 'dragon_orb',
      name: 'Dragon Orb',
      shortName: 'Beam Chain',
      description: 'Beam damage +35% per stack, beam width increases per stack, and beam hits chain to up to 2 nearby enemies.',
      rarity: 'wizard',
      color: '#b77dff',
      category: 'wizard',
      tags: ['beam', 'spell', 'wizard'],
    },
    overstimulate: {
      key: 'overstimulate',
      name: 'Overstimulate',
      shortName: 'Status Stun',
      description: 'Hits have a 20% chance per stack to stun enemies with 2 or more statuses, and the stun lasts twice as long.',
      rarity: 'wizard',
      color: '#ffcf80',
      category: 'wizard',
      tags: ['stun', 'status', 'wizard'],
    },
    grave_zone: {
      key: 'grave_zone',
      name: 'Grave Zone',
      shortName: 'Push Zone',
      description: 'On kill, 25% chance per stack to create a 2.5-second knockback field that makes enemies inside take +8% player damage per stack, deals small AOE damage (2% chance to freeze), hurls rock debris, and drains 20% of its damage back as healing. Above 4 stacks, chance loops to 80% and cold enemies take +50% damage.',
      rarity: 'wizard',
      color: '#c9b3ff',
      category: 'wizard',
      tags: ['aoe', 'knockback', 'wizard'],
    },
    ricocete: {
      key: 'ricocete',
      name: 'Ricocete',
      shortName: 'Bounce +1',
      description: 'Player projectiles get 1 guaranteed wall bounce, plus a 50% chance per stack for an extra bounce.',
      rarity: 'wizard',
      color: '#9be7ff',
      accent: '#b77dff',
      category: 'wizard',
      tags: ['projectile', 'bounce', 'wizard'],
    },
    drink_master: {
      key: 'drink_master',
      name: 'Potion Master',
      shortName: 'Heal +20% / x2',
      description: 'Potions and other healing sources are 20% more effective per stack. Potions also have a 50% chance per stack to apply twice, capped at 100%.',
      rarity: 'wizard',
      color: '#6dff9b',
      accent: '#f4f6fb',
      category: 'wizard',
      tags: ['healing', 'potion', 'wizard'],
    },
    turtle_shell: {
      key: 'turtle_shell',
      name: 'Turtle Shell',
      shortName: 'Shell +5%',
      description: 'Move speed +5% per stack.',
      rarity: 'knight',
      color: '#d2ffd8',
      category: 'knight',
      tags: ['speed', 'move'],
    },
    anchor_charm: {
      key: 'anchor_charm',
      name: 'Anchor Charm',
      shortName: 'Stun Resist',
      description: 'Stun + knockback resistance per stack. Impact stuns on you last less and need harder hits or stronger knockback, and incoming knockback shoves you 12% less per stack (capped at 65% reduction).',
      rarity: 'knight',
      color: '#d7e4f2',
      category: 'knight',
      tags: ['defense', 'stun'],
    },
    iron_lung: {
      key: 'iron_lung',
      name: 'Iron Lung',
      shortName: 'Iron',
      description: 'In non-boss fights, each hit can take at most 20% max HP.',
      rarity: 'god',
      color: '#c6d4e8',
      category: 'god',
      tags: ['defense', 'god'],
    },
    pendant_of_rock: {
      key: 'pendant_of_rock',
      name: 'Pendant of Rock',
      shortName: 'Rock Pact',
      description: 'Per stack: take 1% less damage and deal 2% more rock damage (Crimson Smash debris, Wall of Toph, Laser Shockwave and other rock attacks).',
      rarity: 'god',
      color: '#b89272',
      accent: '#e6c9a3',
      category: 'god',
      tags: ['defense', 'damage', 'rock', 'god'],
    },
    iron_helm: {
      key: 'iron_helm',
      tool: true,
      name: 'Iron Helm',
      shortName: 'Diamond Shield',
      description: 'Tool. Add a diamond shield worth 50% of max HP. Reusing refreshes the shield to that amount. 120s cooldown.',
      rarity: 'god',
      color: '#c8fbff',
      accent: '#f5feff',
      category: 'god',
      tags: ['tools', 'defense', 'shield', 'god'],
    },
    oracles_lens: {
      key: 'oracles_lens',
      name: "Oracle's Lens",
      shortName: 'Oracle',
      description: 'Having at least one doubles critical hit chance, and crits scale harder with your crit chance.',
      rarity: 'god',
      color: '#8ee6ff',
      category: 'god',
      reveal: true,
      tags: ['crit', 'god'],
    },
    homing_missile: {
      key: 'homing_missile',
      name: 'Homing Missile',
      shortName: 'Missiles',
      description: '15% chance per stack to launch 2 fast homing missiles when using R. Missiles fly 3x faster, deal +10% damage, and have a 5% chance to ignite.',
      rarity: 'god',
      color: '#ffe06f',
      category: 'god',
      tags: ['missile', 'god', 'smash'],
    },
    wizards_paw: {
      key: 'wizards_paw',
      name: "Wizard's Paw",
      shortName: 'Paw',
      description: 'Choose 2 stats to increase by 50%. Duplicated pickups grant another choice.',
      opensUi: 'wizardPaw',
      rarity: 'god',
      color: '#ffcf80',
      category: 'god',
      tags: ['god', 'stat'],
    },
    jesters_dice: {
      key: 'jesters_dice',
      name: "Jester's Dice",
      shortName: 'Dice',
      description: 'Skip 3 floors and gain 10 random items per stack collected.',
      rarity: 'god',
      color: '#ff8bd8',
      category: 'god',
      tags: ['god', 'chaos'],
    },
    shield_of_aegis: {
      key: 'shield_of_aegis',
      name: 'Shield of Aegis',
      shortName: 'DEF +20%',
      description: 'Defense +20% per stack (capped with other defense at 85%). On every floor, heal 2% max HP and gain a 50-point shield per stack.',
      rarity: 'god',
      color: '#ffe7a8',
      category: 'god',
      tags: ['god', 'defense'],
    },
    pendant_of_kronos: {
      key: 'pendant_of_kronos',
      name: 'Pendant of Kronos',
      shortName: 'Crit+Dmg/God',
      description: 'For each god (yellow) item you have: +5% crit chance and +2.5% damage. Also +5% damage to bosses.',
      rarity: 'god',
      color: '#d8c6ff',
      category: 'god',
      tags: ['god', 'crit'],
    },
    robot_arm: {
      key: 'robot_arm',
      name: 'Robot Arm',
      shortName: 'Auto x8 Spd',
      description: 'Have Alvin the AI do it While in combat and charged attack speed x8 and your primary attack automatically fires once. Starts ready, then recharges on 8 kills.',
      rarity: 'god',
      color: '#c0e8ff',
      category: 'god',
      tags: ['god', 'speed', 'charge'],
    },
    rich_mans_luck: {
      key: 'rich_mans_luck',
      name: "Rich Man's Luck",
      shortName: 'Shop + Drops',
      description: 'Adds +1 relic offer to shops per stack, and item drops from vases and enemies are 5% more likely per stack.',
      rarity: 'god',
      color: '#ffd76d',
      accent: '#79ffbf',
      category: 'god',
      tags: ['god', 'loot', 'shop'],
    },
    rich_mans_blues: {
      key: 'rich_mans_blues',
      name: "Rich Man's Blues",
      shortName: 'Loop Crystals',
      description: "King's lament: I could lose every penny. Gain 25 Loop Crystals plus 2 per floor counted this run when collected. Each stack grants +1 Loop Crystal after every boss kill.",
      rarity: 'blue',
      color: '#4da8ff',
      accent: '#b9e3ff',
      category: 'artificer',
      tags: ['artificer', 'loot', 'loop'],
    },
    artificer_charger: {
      key: 'artificer_charger',
      name: 'Artificer Charger',
      shortName: 'Holy Light',
      description: 'A great tool of the cult; in holy hands it can send light. Doubles your current level, improves every future level gain, and makes your sprite and AOEs 26.7% larger. Lasers are 5% wider. Picking up a second one costs 1 Loop Crystal to contain — with no crystals, it does nothing.',
      rarity: 'blue',
      color: '#69c8ff',
      accent: '#fff3ae',
      category: 'artificer',
      tags: ['artificer', 'level', 'aoe', 'beam'],
    },
    cloak_of_naked_king: {
      key: 'cloak_of_naked_king',
      name: 'Cloak of the Naked King',
      shortName: 'Cursed Guard',
      description: '(He has lost it.) Negative status effects are 20% worse per stack, including damage, duration, effectiveness, and proc chance. Reduce incoming damage by 10 points per stack, plus 1 point per owned tool stack, equipped or not.',
      rarity: 'blue',
      color: '#3289d6',
      accent: '#d9f2ff',
      category: 'artificer',
      tags: ['artificer', 'defense', 'status', 'tools'],
    },
    moggys_coat: {
      key: 'moggys_coat',
      name: "Moggy's Coat",
      shortName: 'Ambush Drain',
      description: "Shed by the assassin himself. Killing an enemy while hidden primes the coat: the next combat opens with Dark Drain on every enemy for its first 2 seconds. Each stack adds +1 drain stack.",
      rarity: 'blue',
      color: '#5a78d6',
      accent: '#ff5a5a',
      category: 'artificer',
      tags: ['artificer', 'drain', 'stealth', 'status'],
    },
    veggys_pendant: {
      key: 'veggys_pendant',
      name: "Veggy's Pendant",
      shortName: 'Pendant',
      description: 'On pickup, gain +4% max HP per stack. Every 3 rooms entered, gain +10% max HP per stack and heal for 50% of the max HP gained.',
      rarity: 'wizard',
      color: '#a0e87a',
      accent: '#5fcc2a',
      category: 'wizard',
      tags: ['hp', 'scaling', 'wizard'],
    },
    procy_pickle: {
      key: 'procy_pickle',
      name: 'Procy Pickle',
      shortName: 'Pickle',
      description: 'A briny green veggy that loves a chain reaction. +5% per stack chance, whenever you crit or a status-applying item procs, to spread the hit enemy’s statuses to nearby foes. Activating a tool also has a 2% per stack × per tool you own chance to slap nearby enemies with self-spreading poison.',
      rarity: 'god',
      color: '#7bd44f',
      accent: '#cdf58f',
      category: 'god',
      tags: ['poison', 'status', 'spread', 'tools', 'crit', 'god'],
    },
    princes_glasses: {
      key: 'princes_glasses',
      name: "Prince's Glasses",
      shortName: 'Map Vision',
      description: 'Pink, not that anything is wrong with that. Upgrades the minimap: skull markers for traps, enemy dots, green for healing, yellow for coins. First stack grants +5% crit chance and +10% defense; each extra stack adds +2% to both.',
      rarity: 'wizard',
      color: '#ff9de8',
      accent: '#ff55cc',
      category: 'wizard',
      tags: ['minimap', 'utility'],
    },
    mateos_bag: {
      key: 'mateos_bag',
      tool: true,
      name: "Mateo's Bag",
      shortName: 'Bag',
      description: 'Carry potions instead of consuming them immediately. First stack: +3 slots. Each additional stack: +1 slot. Stored potions heal +10% per stack and auto-trigger below 10% health. If empty, entering a shop stores 1 minor potion once per floor.',
      rarity: 'wizard',
      color: '#b49cff',
      category: 'wizard',
      tags: ['potion', 'utility', 'wizard'],
    },
    extra_battery: {
      key: 'extra_battery',
      name: 'Extra Battery',
      shortName: 'Move +1 Stack',
      description: 'Opens a selection of your moves — pick one to grant it +1 max stack. Duplicated pickups grant another choice.',
      opensUi: 'extraBattery',
      rarity: 'wizard',
      color: '#cfd7ff',
      accent: '#7a9dff',
      category: 'wizard',
      tags: ['move', 'stack', 'utility', 'wizard'],
    },
    mooggy_zoomies: {
      key: 'mooggy_zoomies',
      name: 'Mooggy Zoomies',
      shortName: 'Proj Tech',
      description: 'Projectile speed +12% per stack, projectile lifetime/range +10% per stack, and projectile magnetism +2% per stack.',
      rarity: 'wizard',
      color: '#ff3348',
      accent: '#f4f6fb',
      category: 'wizard',
      tags: ['projectile', 'speed', 'wizard'],
    },
    el_bartos_cape: {
      key: 'el_bartos_cape',
      tool: true,
      name: "El Barto's Cape",
      shortName: 'CAPE',
      description: 'Tool. Activate for 10 seconds; you are invisible for the first half and move 20% faster while active. Your first hit while active is a guaranteed crit that applies bleed and poison. Each stack adds +5 seconds and a +10% chance on use to leave damaging El Barto graffiti; graffiti is guaranteed at 3+ stacks.',
      rarity: 'god',
      color: '#ff5b78',
      accent: '#ffe0b8',
      category: 'god',
      tags: ['tools', 'stealth', 'god'],
    },
    voucher_white: {
      key: 'voucher_white',
      name: 'White Voucher',
      shortName: 'White Voucher',
      description: 'Redeem at a shop to choose any Knight-class relic.',
      rarity: 'knight',
      color: '#f4f6fb',
      accent: '#9bd9ff',
      category: 'knight',
      voucher: true,
      tags: ['voucher', 'choice', 'knight'],
    },
    voucher_purple: {
      key: 'voucher_purple',
      name: 'Purple Voucher',
      shortName: 'Purple Voucher',
      description: 'Redeem at a shop to choose any Wizard-class relic.',
      rarity: 'wizard',
      color: '#b77dff',
      accent: '#f4d4ff',
      category: 'wizard',
      voucher: true,
      tags: ['voucher', 'choice', 'wizard'],
    },
    voucher_yellow: {
      key: 'voucher_yellow',
      name: 'Yellow Voucher',
      shortName: 'Yellow Voucher',
      description: 'Redeem at a shop to choose any God-class relic.',
      rarity: 'god',
      color: '#ffd23f',
      accent: '#fff6cf',
      category: 'god',
      voucher: true,
      tags: ['voucher', 'choice', 'god'],
    },
    forge_voucher: {
      key: 'forge_voucher',
      name: 'Forge Voucher',
      shortName: 'Forge x5',
      description: 'Redeem at the Forge for 5 free weapon or move upgrade steps before XP or gold is spent.',
      rarity: 'knight',
      color: '#ffb840',
      accent: '#fff1a8',
      category: 'knight',
      voucher: true,
      tags: ['voucher', 'forge', 'upgrade', 'utility'],
    },
    // --- GREEN tier: post-loop drop-only items whose descriptions LIE. ---
    // The shown `description` is the fib; the true effect is applied in code (see
    // realNote + getItemStats / pickup hooks). Do not "fix" the descriptions to
    // match the effects — the mismatch is the point.
    naked_kings_last_penny: {
      key: 'naked_kings_last_penny',
      name: "Naked King's Last Penny",
      shortName: 'Last Penny',
      description: 'Gives you one extra coin per stack whenever you pick up gold. Every penny counts when the crown is all you have left.',
      // realNote: +7 gold the first time you reveal a room (+20% per extra stack),
      // and every coin pickup re-plays the gold-gain sound and grants +1 coin per stack.
      rarity: 'green',
      color: '#3ef07a',
      accent: '#ffe07a',
      category: 'green',
      tags: ['coin', 'loot', 'lie'],
    },
    foleys_irish_newyork_charm: {
      key: 'foleys_irish_newyork_charm',
      name: "Foley's Irish NewYork Charm",
      shortName: 'Foley Charm',
      description: 'A bit on the nose and runny. Makes you hit something when you attack by 0.2%. Makes you rich — we are all gonna be rich. If he has two yachts, we will have ten.',
      // realNote: just gives +15 max HP and +1 on-hit damage per stack. Doesn't do much.
      rarity: 'green',
      color: '#3ef07a',
      accent: '#7fffb0',
      category: 'green',
      tags: ['health', 'damage', 'hit', 'lie'],
    },
    paul_cunts_house_keys: {
      key: 'paul_cunts_house_keys',
      name: "Paul Cunt's House Keys",
      shortName: 'House Keys',
      description: 'Go get him! Address in the URL metadata!! Makes you better and stronger than everyone, and so good with money. ;)',
      // realNote: once per floor you may "strike a rival" from the inventory Rivals
      // tab — remotely damaging that rival (or killing a random enemy near them).
      rarity: 'green',
      color: '#3ef07a',
      accent: '#9bd84f',
      category: 'green',
      tags: ['rival', 'utility', 'lie'],
    },
  };

// Moment-to-moment UI uses these compact mechanical summaries. The full copy in
// ITEM_DEFS.description remains the Item Index source of truth. Green relics are
// deliberately excluded: their long, misleading descriptions are part of their
// design and must be shown unchanged everywhere.
const ITEM_SHORT_DESCRIPTIONS = Object.freeze({
  neo_knife: '+10% melee Bleed chance per stack.',
  tooth_of_thorn: 'Hits can drain enemy life and heal you.',
  tough_bandaid: 'Gain defense, Bleed chance, and Bleed resistance.',
  orb_of_blood: 'Bleeding enemies take +100% damage per stack.',
  hemes_scarf: 'Bleed nearby enemies; charged blood restores low HP.',
  insurance: 'Survive a hit below half HP, then recharge with kills.',
  gold_vac: 'Tool: vacuum pickups and multiply collected coins.',
  copycat_charm: 'Chance to duplicate item pickups.',
  crit_charm: 'Gain crit chance and periodic kill-powered crit surges.',
  copper_penny: 'Electric attacks deal more damage and build Static.',
  attack_servo: '+8% attack speed per stack.',
  enemy_magnet: 'Projectiles gain increasingly strong homing.',
  keen_eye: 'Kills charge a powerful temporary crit boost.',
  chrono_spring: 'Kills charge a temporary attack-speed boost.',
  scholar_seal: 'Gain more kill XP and near-level shop discounts.',
  scholar_cap: 'Deal more damage as you approach the next level.',
  push_man: '+18% knockback per stack.',
  titan_heart: '+8% max HP per stack.',
  weapon_fatigue: 'Hits can slow or briefly freeze enemies.',
  generic_health_item: 'Kills restore HP; overhealing can grant a shield.',
  snake_knife: 'Hits can poison; poison may spread between enemies.',
  confuse_ray: 'Hits can stun or make enemies lose track of you.',
  overclocked_watch: 'Kills can grant double charge progress.',
  charged_adapter: 'Tool: spend half your coins to warp to the exit.',
  pew_pew_box: 'Tool: fire volleys of homing missiles.',
  skizzard_tail: 'Tool: regenerate health over time.',
  zap_to_extreme: 'Tool: unleash chain lightning around you.',
  panic_button: 'Tool: cleanse, repel enemies, and become briefly invulnerable.',
  mid_sweepy_box: 'Tool: sweep explosive Bleed mines around you.',
  sparkle_charm: 'Tool: mark enemies so every hit critically strikes.',
  churu_stick: 'Tool: instantly heal 30% max HP.',
  explosive_jelly: '+20% AOE range per stack.',
  dragon_orb: 'Beams deal more damage, widen, and chain to enemies.',
  overstimulate: 'Status-loaded enemies can be stunned for longer.',
  grave_zone: 'Kills can create a damaging, healing knockback field.',
  ricocete: 'Projectiles gain guaranteed and bonus wall bounces.',
  drink_master: 'Healing is stronger; potions can trigger twice.',
  turtle_shell: '+5% move speed per stack.',
  anchor_charm: 'Resist stuns and incoming knockback.',
  iron_lung: 'Non-boss hits cannot exceed 20% max HP.',
  pendant_of_rock: 'Take less damage and deal more rock damage.',
  iron_helm: 'Tool: create a shield worth 50% max HP.',
  oracles_lens: 'Double crit chance and improve crit scaling.',
  homing_missile: 'Smash attacks can launch two homing missiles.',
  wizards_paw: 'Choose two stats to increase by 50%.',
  jesters_dice: 'Skip three floors and gain ten random items.',
  shield_of_aegis: 'Gain defense, floor healing, and a recurring shield.',
  pendant_of_kronos: 'God relics grant crit and damage bonuses.',
  robot_arm: 'Kills charge one automatic, ultra-fast primary attack.',
  rich_mans_luck: 'Shops offer more relics and enemies drop more items.',
  rich_mans_blues: 'Gain Loop Crystals now and after boss kills.',
  artificer_charger: 'Double your level and enlarge your character and AOEs.',
  cloak_of_naked_king: 'Statuses hurt more, but incoming hits lose flat damage.',
  moggys_coat: 'Hidden kills prime an opening Dark Drain ambush.',
  veggys_pendant: 'Gain max HP now and every three rooms.',
  procy_pickle: 'Crits, status procs, and tools can spread statuses.',
  princes_glasses: 'Upgrade the minimap and gain crit and defense.',
  mateos_bag: 'Store potions for stronger healing and emergency use.',
  extra_battery: 'Choose one move to gain +1 max stack.',
  mooggy_zoomies: 'Projectiles gain speed, range, and magnetism.',
  el_bartos_cape: 'Tool: turn invisible, move faster, and empower your first hit.',
  voucher_white: 'Choose any Knight relic at a shop.',
  voucher_purple: 'Choose any Wizard relic at a shop.',
  voucher_yellow: 'Choose any God relic at a shop.',
  forge_voucher: 'Gain five free Forge upgrade steps.',
});

function getItemShortDescription(itemOrKey) {
  const item = typeof itemOrKey === 'string' ? ITEM_DEFS[itemOrKey] : itemOrKey;
  if (!item) return '';
  if ((item.rarity || item.category) === 'green') return item.description || '';
  return ITEM_SHORT_DESCRIPTIONS[item.key] || item.shortDescription || item.description || '';
}

Object.values(ITEM_DEFS).forEach(item => {
  item.shortDescription = getItemShortDescription(item);
});
// Scrolls are their own system, kept out of ITEM_DEFS / the relic pools. They are
// registered into the item registry (see createItemRegistry) so runtime lookups —
// icons, rarity, tags, names, shop offers, save/load — resolve scroll keys the same
// way as relics, but they never appear in the relic codex tab or random relic pools.
// Each scroll resolves its selection popup on pickup/purchase (see enqueueScrollSelection).
const SCROLL_DEFS = {
    scroll_reroll: {
      key: 'scroll_reroll',
      name: 'Scroll of Reroll',
      shortName: 'Reroll',
      description: 'Choose one owned relic and replace one stack with a new relic of the same rarity.',
      rarity: 'knight',
      color: '#d9f2ff',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'choice'],
    },
    scroll_branching: {
      key: 'scroll_branching',
      name: 'Scroll of Branching',
      shortName: 'Branch',
      description: 'Choose a relic. The next reward of that relic rarity becomes your chosen relic.',
      rarity: 'knight',
      color: '#d8ffc5',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'choice'],
    },
    scroll_replace: {
      key: 'scroll_replace',
      name: 'Scroll of Replace',
      shortName: 'Replace',
      description: 'Choose an unwanted relic, then choose a same-rarity replacement. Future rewards swap it.',
      rarity: 'knight',
      color: '#ffd9d9',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'choice'],
    },
    scroll_abundance: {
      key: 'scroll_abundance',
      name: 'Scroll of Abundance',
      shortName: 'Abundance',
      description: 'Choose two relics. Every two floors has a chance to grant one selected relic or one random relic.',
      rarity: 'knight',
      color: '#fff2a8',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'choice'],
    },
    scroll_pool_weight: {
      key: 'scroll_pool_weight',
      name: 'Scroll of Pool Weight',
      shortName: 'Weight',
      description: 'Choose one of 4 relics. Future rewards favor that relic for 3 floors, with rarity-scaled strength.',
      rarity: 'knight',
      color: '#c8e2ff',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'choice'],
    },
    scroll_ego: {
      key: 'scroll_ego',
      name: 'Scroll of Ego',
      shortName: 'Ego',
      description: 'For this floor, relics already in your build are 10% more common.',
      rarity: 'knight',
      color: '#f4d4ff',
      category: 'knight',
      tool: true,
      scroll: true,
      opensUi: 'scrollControl',
      tags: ['scroll', 'control', 'build'],
    },
  };
const SCROLL_KEYS = Object.keys(SCROLL_DEFS);

  return { ITEM_DEFS, ITEM_SHORT_DESCRIPTIONS, getItemShortDescription, SCROLL_DEFS, SCROLL_KEYS };
});

